# Generated by Django 6.0.7 on 2026-07-26 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(unique=True)),
                ('kicker', models.CharField(blank=True, max_length=80)),
                ('titulo', models.CharField(max_length=120)),
                ('subtitulo', models.CharField(blank=True, max_length=200)),
                ('objetivo', models.TextField(blank=True)),
                ('duracion', models.CharField(blank=True, max_length=60)),
                ('horas', models.CharField(blank=True, max_length=60)),
                ('color', models.CharField(default='#c2703d', max_length=7)),
            ],
            options={
                'verbose_name_plural': 'Etapas',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('curso', 'Curso'), ('libro', 'Libro'), ('entregable', 'Entregable'), ('nota', 'Nota')], default='curso', max_length=20)),
                ('titulo', models.CharField(max_length=250)),
                ('fuente', models.CharField(blank=True, help_text='Platzi, Udemy, autor del libro…', max_length=80)),
                ('detalle', models.TextField(blank=True)),
                ('etiqueta', models.CharField(blank=True, help_text='Hábitos, Ficción, Foco…', max_length=40)),
                ('en_ingles', models.BooleanField(default=False)),
                ('completado', models.BooleanField(default=False)),
                ('completado_en', models.DateTimeField(blank=True, null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='roadmap.etapa')),
            ],
            options={
                'ordering': ['etapa__orden', 'orden', 'id'],
            },
        ),
    ]
