# Generated by Django 6.0.7 on 2026-07-26 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='generado',
            field=models.BooleanField(default=False, help_text='Item añadido como complemento, no viene del PDF original.'),
        ),
    ]
