# Generated by Django 6.0.7 on 2026-07-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0002_item_generado'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='url',
            field=models.URLField(blank=True, help_text='Enlace directo al curso, libro o recurso.', max_length=500),
        ),
    ]
