# Generated by Django 6.0.7 on 2026-07-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0003_item_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etapa',
            options={'ordering': ['ruta', 'orden'], 'verbose_name_plural': 'Etapas'},
        ),
        migrations.AddField(
            model_name='etapa',
            name='paralela',
            field=models.BooleanField(default=False, help_text='Va en la columna lateral: corre en paralelo, no en secuencia.'),
        ),
        migrations.AddField(
            model_name='etapa',
            name='ruta',
            field=models.CharField(choices=[('completo', 'Roadmap completo'), ('enfocada', 'Ruta enfocada AI/ML Engineer')], default='completo', help_text='A qué recorrido pertenece esta etapa.', max_length=20),
        ),
        migrations.AlterField(
            model_name='etapa',
            name='orden',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddConstraint(
            model_name='etapa',
            constraint=models.UniqueConstraint(fields=('ruta', 'orden'), name='etapa_orden_unico_por_ruta'),
        ),
    ]
