# Generated by Django 6.0.7 on 2026-07-27 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0004_alter_etapa_options_etapa_paralela_etapa_ruta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapa',
            name='oculta',
            field=models.BooleanField(default=False, help_text='No se dibuja en el mapa. Para contenedores como la biblioteca.'),
        ),
    ]
