"""La biblioteca: todos los libros, en un solo lugar y sin ruta que los ate.

Los libros no son parte del plan de doce meses —no tienen fecha ni orden— así
que viven en una etapa aparte, marcada como oculta: no se dibuja en el mapa,
pero su contenido alimenta la columna de lectura de la página.

Este archivo es la unión, sin repetidos, de todos los libros que estaban
repartidos por el catálogo viejo. Los que traían enlace lo conservan; a los
demás se les genera uno de búsqueda en Open Library.

    python manage.py cargar_biblioteca
    python manage.py cargar_biblioteca --quitar
"""

from urllib.parse import quote_plus

from django.core.management.base import BaseCommand
from django.db import transaction

from roadmap.models import Etapa, Item

OL = "https://openlibrary.org/search?q="

ORDEN_BIBLIOTECA = 99

# (título, autor, por qué leerlo, etiqueta, en_inglés[, url])
LIBROS = [
    ("Clean Code", "Robert C. Martin", "El libro de referencia para aprender a escribir código legible, estructurado y profesional.", "Programación", True),
    ("Fundamentals of Data Engineering", "Joe Reis y Matt Housley", "El mapa completo del oficio antes de meterte en herramientas sueltas.", "Referencia", True),
    ("Python Crash Course", "Eric Matthes", "Dominio práctico de Python orientado a proyectos reales.", "Python", True),
    ("The Pragmatic Programmer", "Andrew Hunt y David Thomas", "Filosofía fundamental del desarrollo de software y artesanía de código.", "Carrera", True),
    ("Grokking Algorithms", "Aditya Bhargava", "Una guía ilustrada para entender algoritmos complejos de manera intuitiva.", "Algoritmos", True),
    ("Code: The Hidden Language of Computer Hardware and Software", "Charles Petzold", "Cómo se conectan el hardware y el software desde puertas lógicas básicas.", "Computación", True),
    ("Structure and Interpretation of Computer Programs", "Harold Abelson", "Fundamentos profundos de abstracción en ciencias de la computación.", "Computación", True),
    ("The Linux Command Line", "William Shotts", "Guía exhaustiva para dominar la línea de comandos de Linux.", "Linux", True),
    ("Make It Stick: The Science of Successful Learning", "Peter C. Brown", "Estrategias de aprendizaje eficaz basadas en ciencia cognitiva.", "Aprendizaje", True),
    ("Mindset: La psicología del éxito", "Carol S. Dweck", "Mentalidad de crecimiento indispensable para transformarte profesionalmente.", "Psicología", False),
    ("El gen egoísta", "Richard Dawkins", "Una perspectiva biológica revolucionaria sobre la evolución y el comportamiento.", "Ciencia", True),
    ("El universo elegante", "Brian Greene", "Supercuerdas, dimensiones ocultas y la búsqueda de la teoría definitiva en física.", "Física", True),
    ("Sapiens: De animales a dioses", "Yuval Noah Harari", "Breve historia de la humanidad y las revoluciones que moldearon la sociedad.", "Historia", True),
    ("Discurso del método", "René Descartes", "La base del pensamiento racionalista y el método científico moderno.", "Filosofía", True),
    ("Cartas a Lucilio", "Séneca", "Consejos de estoicismo práctico para mantener la templanza en la vida diaria.", "Filosofía", True),
    ("Manual para la vida", "Epicteto", "Enseñanzas sobre lo que está bajo nuestro control y lo que debemos aceptar.", "Filosofía", True),
    ("Ética a Nicómaco", "Aristóteles", "La búsqueda de la virtud, la justicia y la eudaimonía (plenitud).", "Filosofía", True),
    ("La república", "Platón", "Diálogo sobre la justicia, la educación, la política y la alegoría de la caverna.", "Filosofía", True),
    ("Ensayo sobre el entendimiento humano", "John Locke", "Origen y límites del conocimiento humano desde el empirismo.", "Filosofía", True),
    ("Don Quijote de la Mancha", "Miguel de Cervantes", "Obra cumbre de la literatura en español sobre el idealismo y la realidad.", "Literatura", True),
    ("Cien años de soledad", "Gabriel García Márquez", "Obra maestra del realismo mágico e historia de la familia Buendía.", "Literatura", True),
    ("El príncipe", "Nicolás Maquiavelo", "Tratado clásico sobre la política, el poder y la estrategia de estado.", "Historia", True),
    ("1984", "George Orwell", "Novela distópica sobre el totalitarismo, la vigilancia y la manipulación de la verdad.", "Literatura", True),
    ("Fahrenheit 451", "Ray Bradbury", "Una crítica sobre la censura, el conocimiento y el valor de los libros.", "Literatura", True),
    ("Un mundo feliz", "Aldous Huxley", "Reflexión sobre una sociedad condicionada tecnológicamente al placer superficial.", "Literatura", True),
    ("El principito", "Antoine de Saint-Exupéry", "Fábula filosófica sobre el amor, la amistad, la inocencia y la condición humana.", "Filosofía", False),
    ("Los cuatro acuerdos", "Don Miguel Ruiz", "Guía práctica de sabiduría tolteca para la libertad personal y la eliminación de creencias limitantes.", "Autoconocimiento", False),
    ("Tus Zonas Erróneas", "Wayne W. Dyer", "Principios para superar pensamientos autodestructivos, culpa y dependencia emocional.", "Autoconocimiento", False),
    ("El cerebro y la inteligencia emocional", "Daniel Goleman", "Hallazgos sobre el funcionamiento cerebral, la autorregulación emocional y el rendimiento.", "Autoconocimiento", False),
    ("El monje que vendió su Ferrari", "Robin Sharma", "Fábula espiritual sobre cómo vivir con sentido, foco y equilibrio personal.", "Autoconocimiento", False),
    ("Aprender a aprender", "Barbara Oakley", "Técnicas científicas de estudio, memoria y superación de la procrastinación.", "Aprendizaje", False),
    ("Los desafíos de la memoria", "Joshua Foer", "Investigación periodística y práctica sobre cómo funciona la memoria y los palacios de la memoria.", "Productividad", False),
    ("El sutil arte de que te importe un carajo", "Mark Manson", "Enfoque realista y contraintuitivo sobre la gestión de prioridades y valores personales.", "Autoconocimiento", False),
    ("Focus", "Daniel Goleman", "El valor de la atención, la concentración profunda y la empatía en un mundo distráido.", "Productividad", False),
    ("Los 7 hábitos de la gente altamente efectiva", "Stephen Covey", "Principios fundamentales para la efectividad personal e interpersonal sostenible.", "Productividad", False),
    ("El poder del ahora", "Eckhart Tolle", "Guía de iluminación espiritual e introspección sobre la presencia consciente.", "Autoconocimiento", False),
    ("En defensa de la Ilustración", "Steven Pinker", "Análisis basado en datos sobre el progreso humano, la razón, la ciencia y el humanismo.", "Filosofía", False),
    ("Designing Data-Intensive Applications", "Martin Kleppmann", "El libro técnico de referencia para sistemas distribuidos y datos.", "Referencia", True),
    ("Data Pipelines Pocket Reference", "James Densmore", "Guía práctica con patrones para construir y orquestar pipelines.", "Pipelines", True),
    ("Building Data Pipelines with Python", "Bas P. van Beek", "Arquitectura de datos mantenible y patrones de pipelines con Python.", "Pipelines", True),
    ("Data Engineering with AWS", "Gareth Eagar", "Construcción de soluciones de datos escalables en la nube de AWS.", "AWS", True),
    ("Database Internals", "Alex Petrov", "Estructuras de almacenamiento, árboles B+, WAL y motores de bases de datos.", "Bases de Datos", True),
    ("Streaming Systems", "Tyler Akidau", "Modelos de procesamiento de eventos en tiempo real y semantics exactas.", "Streaming", True),
    ("System Design Interview – An Insider's Guide", "Alex Xu", "Diseño de sistemas distribuidos a gran escala explicado de forma práctica.", "Arquitectura", True),
    ("Data Management at Scale", "Piethein Strengholt", "Arquitecturas modernas de datos, Data Mesh y gobierno corporativo.", "Arquitectura", True),
    ("Building Event-Driven Microservices", "Adam Bellemare", "Diseño de sistemas desacoplados basados en eventos y streaming.", "Arquitectura", True),
    ("Accelerate", "Nicole Forsgren et al.", "La ciencia detrás de DevOps y la entrega de software de alto rendimiento.", "DevOps", True),
    ("Breve historia del tiempo", "Stephen Hawking", "Orígenes del universo, hoyos negros y la naturaleza del espacio-tiempo.", "Física", True),
    ("La estructura de las revoluciones científicas", "Thomas S. Kuhn", "Cómo avanzan las ciencias a través de cambios de paradigma.", "Ciencia", True),
    ("La riqueza de las naciones", "Adam Smith", "Cimientos de la economía moderna, división del trabajo y libre mercado.", "Economía", True),
    ("El capital en el siglo XXI", "Thomas Piketty", "Análisis histórico de la acumulación de riqueza y la desigualdad.", "Economía", True),
    ("Los cañones de agosto", "Barbara Tuchman", "Estudio histórico del desencadenamiento de la Primera Guerra Mundial.", "Historia", True),
    ("La lógica de la investigación científica", "Karl Popper", "El principio de falsabilidad y la definición del conocimiento científico.", "Epistemología", True),
    ("Tratado de la naturaleza humana", "David Hume", "Análisis empirista sobre la percepción, la causalidad y las emociones.", "Filosofía", True),
    ("Crítica de la razón pura", "Immanuel Kant", "Investigación sobre los límites del conocimiento a priori y a posteriori.", "Filosofía", True),
    ("Crimen y castigo", "Fiódor Dostoyevski", "Exploración psicológica de la culpa, el dilema moral y la redención.", "Literatura", True),
    ("Los hermanos Karamázov", "Fiódor Dostoyevski", "Novela sobre la fe, la duda, la moral y la dinámica familiar.", "Literatura", True),
    ("Guerra y paz", "León Tolstói", "Monumental retrato de la invasión napoleónica a Rusia y la condición humana.", "Literatura", True),
    ("La odisea", "Homero", "El poema épico clásico sobre el regreso de Odiseo a Ítaca.", "Literatura", True),
    ("La divina comedia", "Dante Alighieri", "El viaje alegórico a través del Infierno, Purgatorio y Paraíso.", "Literatura", True),
    ("Pedro Páramo", "Juan Rulfo", "Obra maestra de la literatura mexicana sobre la memoria, la muerte y el pueblo de Comala.", "Literatura", True),
    ("La montaña mágica", "Thomas Mann", "Reflexión filosófica y cultural ambientada en un sanatorio suizo.", "Literatura", True),
    ("Breves respuestas a las grandes preguntas", "Stephen Hawking", "Reflexiones finales de Hawking sobre el origen del universo, los agujeros negros y la IA.", "Ciencia", False),
    ("El universo en una cáscara de nuez", "Stephen Hawking", "Exploración ilustrada de la física teórica, cosmología y teoría de cuerdas.", "Ciencia", False),
    ("Seis piezas fáciles", "Richard Feynman", "Las explicaciones más esenciales y accesibles de la física elemental por Richard Feynman.", "Ciencia", False),
    ("La realidad no es lo que parece", "Carlo Rovelli", "La evolución de la física desde la antigüedad hasta la gravedad cuántica de bucles.", "Ciencia", False),
    ("El comienzo del infinito", "David Deutsch", "Explicaciones sobre el progreso del conocimiento, la ciencia y la infinitud de las explicaciones.", "Ciencia", False),
    ("Reliability-Centered Maintenance", "John Moubray", "El texto definitivo para entender la confiabilidad operacional.", "Dominio", True),
    ("An Introduction to Statistical Learning", "Gareth James et al.", "Rigor matemático claro aplicado a regresión, clasificación y árboles.", "Estadística", True),
    ("Hands-On Machine Learning with Scikit-Learn, Keras, and TensorFlow", "Aurélien Géron", "La guía práctica indispensable para machine learning y aprendizaje profundo.", "Machine Learning", True),
    ("Forecasting: Principles and Practice", "Rob J Hyndman", "El manual de referencia mundial para predicción de series temporales.", "Series de Tiempo", True),
    ("Feature Engineering and Selection", "Max Kuhn y Kjell Johnson", "Metodologías rigurosas para la preparación de datos predictivos.", "Feature Eng.", True),
    ("Python Data Science Handbook", "Jake VanderPlas", "Manual completo de NumPy, Pandas, Matplotlib y Scikit-Learn.", "Data Science", True),
    ("The Elements of Statistical Learning", "Trevor Hastie et al.", "El tratamiento estadístico avanzado de los algoritmos de machine learning.", "Estadística", True),
    ("Mathematics for Machine Learning", "Marc Peter Deisenroth", "Álgebra lineal, cálculo multivariable y probabilidad para ML.", "Matemáticas", True),
    ("Causal Inference in Statistics: A Primer", "Judea Pearl", "Introducción al análisis causal y modelos estructurales.", "Estadística", True),
    ("Probabilistic Programming & Bayesian Methods for Hackers", "Cameron Davidson-Pilon", "Estadística bayesiana orientada a código y práctica.", "Estadística", True),
    ("El cisne negro", "Nassim Nicholas Taleb", "El impacto de lo altamente improbable y los límites de la predicción.", "Riesgo", True),
    ("¿Existe la suerte? (Fooled by Randomness)", "Nassim Nicholas Taleb", "Sobre cómo tendemos a confundir el azar con la destreza.", "Riesgo", True),
    ("Gödel, Escher, Bach", "Douglas Hofstadter", "Un estudio sobre autorreferencia, mente y matemática.", "Ciencia", True),
    ("El cerebro se cambia a sí mismo", "Norman Doidge", "Historias reales sobre neuroplasticidad y la adaptación cerebral.", "Neurociencia", True),
    ("La tabla rasa", "Steven Pinker", "La naturaleza humana frente al condicionamiento cultural.", "Psicología", True),
    ("Más allá del bien y del mal", "Friedrich Nietzsche", "Crítica a los dogmas filosóficos tradicionales y la voluntad de poder.", "Filosofía", True),
    ("El mito de Sísifo", "Albert Camus", "Ensayo filosófico sobre el absurdo, el sentido y la libertad.", "Filosofía", True),
    ("El hombre en busca de sentido", "Viktor Frankl", "La psicología del significado surgida del sufrimiento en campos de concentración.", "Psicología", True),
    ("El aleph", "Jorge Luis Borges", "Relatos sobre el infinito, el tiempo y los laberintos del pensamiento.", "Literatura", True),
    ("Rayuela", "Julio Cortázar", "La anti-novela innovadora que desafía el orden de lectura tradicional.", "Literatura", True),
    ("Moby Dick", "Herman Melville", "La obsesión épica del capitán Ahab contra la ballena blanca.", "Literatura", True),
    ("El proceso", "Franz Kafka", "La alienación individual frente a una burocracia absurda e impenetrable.", "Literatura", True),
    ("El viejo y el mar", "Ernest Hemingway", "Una metáfora sobre la lucha, el esfuerzo y la dignidad humana.", "Literatura", True),
    ("Ensayo sobre la ceguera", "José Saramago", "Una epidemia de ceguera que desnuda la condición humana.", "Literatura", True),
    ("La metamorfosis", "Franz Kafka", "La transformación de Gregorio Samsa y el aislamiento social.", "Literatura", True),
    ("Factfulness", "Hans Rosling", "Diez razones por las que estamos equivocados sobre el mundo y por qué las cosas están mejor de lo que pensamos.", "Pensamiento", False),
    ("Armas de destrucción matemática", "Cathy O’Neil", "Cómo los algoritmos y el Big Data pueden amplificar la desigualdad y la discriminación.", "Sesgos", False),
    ("Algoritmos para la vida cotidiana", "Brian Christian & Tom Griffiths", "Aplicación de algoritmos informáticos a la toma de decisiones en la vida diaria.", "Algoritmos", False),
    ("El ruido: Una falla en el juicio humano", "Daniel Kahneman", "Estudio sobre la variabilidad indeseada en el juicio humano y cómo reducirla.", "Pensamiento", False),
    ("Pensar en sistemas", "Donella Meadows", "Introducción esencial a la dinámica de sistemas y el análisis de interconexiones complejas.", "Sistemas", False),
    ("Building LLM Apps", "Valentina Alto", "Construcción de aplicaciones reales impulsadas por LLMs.", "LLMs", True),
    ("Generative AI on AWS", "Chris Fregly y Antje Barth", "Implementación y escalado de IA generativa corporativa.", "Generative AI", True),
    ("Designing Autonomous AI Agents", "Harrison Chase", "Patrones de arquitectura para agentes autónomos.", "Agentes", True),
    ("AI Engineering: Building Applications with Foundation Models", "Chip Huyen", "Ingeniería de software adaptada a sistemas deterministas y estocásticos.", "AI Engineering", True),
    ("Deep Learning", "Ian Goodfellow et al.", "El libro de texto clásico sobre redes neuronales profundas.", "AI Engineering", True),
    ("Reinforcement Learning: An Introduction", "Richard S. Sutton", "Fundamentos de aprendizaje por refuerzo.", "AI Engineering", True),
    ("Natural Language Processing with Transformers", "Lewis Tunstall et al.", "Construcción y fine-tuning de modelos Hugging Face.", "NLP", True),
    ("Speech and Language Processing", "Daniel Jurafsky", "La biblia del procesamiento de lenguaje natural.", "NLP", True),
    ("Vector Search Architecture", "Mohamed Ali", "Diseño de índices vectoriales e infraestructura de búsqueda semántica.", "Vector DB", True),
    ("Enterprise RAG Systems", "James Wilson", "Patrones de producción para sistemas Retrieval-Augmented Generation.", "RAG", True),
    ("Superinteligencia", "Nick Bostrom", "Caminos, peligros y estrategias ante la Inteligencia Artificial General.", "Futuro", True),
    ("La era del capitalismo de la vigilancia", "Shoshana Zuboff", "Análisis sobre el uso corporativo de los datos de comportamiento humano.", "Sociedad", True),
    ("La señal y el ruido", "Nate Silver", "Cómo distinguir la información relevante entre tanto dato desordenado.", "Estadística", True),
    ("Imparables: Diario de un científico", "Neil deGrasse Tyson", "Reflexiones sobre el conocimiento científico y la exploración.", "Ciencia", True),
    ("Cosmos", "Carl Sagan", "La historia de la ciencia y la visión humana del universo.", "Ciencia", True),
    ("Tractatus Logico-Philosophicus", "Ludwig Wittgenstein", "Los límites del lenguaje y su relación con la realidad.", "Filosofía", True),
    ("Leviatán", "Thomas Hobbes", "Sobre la estructura de la sociedad, el contrato social y el poder.", "Filosofía", True),
    ("Así habló Zaratustra", "Friedrich Nietzsche", "Filosofía del superhombre y la transvaloración de los valores.", "Filosofía", True),
    ("Dune", "Frank Herbert", "Obra maestra de la ciencia ficción sobre ecología, política y religión.", "Literatura", True),
    ("Fundación", "Isaac Asimov", "La psicohistoria y la reconstrucción de la civilización galáctica.", "Literatura", True),
    ("Yo, Robot", "Isaac Asimov", "Relatos clásicos sobre las tres leyes de la robótica y sus dilemas.", "Literatura", True),
    ("Neuromante", "William Gibson", "La novela pionera del género cyberpunk que acuñó el término ciberespacio.", "Literatura", True),
    ("El problema de los tres cuerpos", "Cixin Liu", "Trilogía de ciencia ficción china sobre el contacto con una civilización ajena.", "Literatura", True),
    ("¿Sueñan los androides con ovejas eléctricas?", "Philip K. Dick", "Reflexión sobre qué nos hace humanos frente a réplicas artificiales.", "Literatura", True),
    ("Guía del autoestopista galáctico", "Douglas Adams", "Sátira cómica y absurda de la ciencia ficción.", "Literatura", True),
    ("Crónicas marcianas", "Ray Bradbury", "Relatos entrelazados sobre la colonización de Marte y la naturaleza humana.", "Ficción", False),
    ("La guerra de los mundos", "H.G. Wells", "La novela clásica pionera sobre invasiones extraterrestres y resistencia.", "Ficción", False),
    ("Never Split the Difference", "Chris Voss", "Negociación táctica de ofertas laborales y salarios internacionales.", "Negociación", True),
    ("The Hard Thing About Hard Things", "Ben Horowitz", "Gestión de la incertidumbre y la resiliencia en situaciones difíciles.", "Liderazgo", True),
    ("Essentialism: The Disciplined Pursuit of Less", "Greg McKeown", "Enfoque deliberado en lo verdaderamente esencial.", "Productividad", True),
    ("The Personal MBA", "Josh Kaufman", "Conceptos clave de negocios, finanzas y estrategia comercial.", "Negocios", True),
    ("Crucial Conversations", "Kerry Patterson", "Habilidades de comunicación para escenarios de alta presión.", "Comunicación", True),
    ("Influence: The Psychology of Persuasion", "Robert Cialdini", "Los seis principios universales de persuasión e influencia.", "Psicología", True),
    ("Good to Great", "Jim Collins", "Por qué algunas empresas dan el salto hacia la excelencia y otras no.", "Negocios", True),
    ("High Output Management", "Andrew Grove", "Principios de gestión de equipos por el legendario CEO de Intel.", "Liderazgo", True),
    ("Principles for Dealing with the Changing World Order", "Ray Dalio", "Análisis histórico de los grandes ciclos económicos y geopolíticos.", "Economía", True),
    ("The Intelligent Investor", "Benjamin Graham", "La biblia del valor de inversión y finanzas personales.", "Finanzas", True),
    ("Zero to One", "Peter Thiel", "Cómo construir startups que creen un futuro verdaderamente nuevo.", "Estrategia", True),
    ("Thinking in Bets", "Annie Duke", "Toma de decisiones inteligentes cuando no tienes toda la información.", "Toma de Decis.", True),
    ("Lombardi on Leadership", "Vince Lombardi", "Principios de ejecución, disciplina y liderazgo de alto impacto.", "Liderazgo", True),
    ("Armas, gérmenes y acero", "Jared Diamond", "Cómo la geografía y el entorno determinaron el destino de las civilizaciones.", "Historia", True),
    ("Historia de la filosofía occidental", "Bertrand Russell", "Recorrido ameno por la historia del pensamiento humano.", "Filosofía", True),
    ("El arte de la guerra", "Sun Tzu", "Principios milenarios de estrategia y resolución de conflictos.", "Estrategia", True),
    ("Homo Deus: Breve historia del mañana", "Yuval Noah Harari", "Hacia dónde se dirige la humanidad en el siglo XXI.", "Historia", True),
    ("Hamlet", "William Shakespeare", "Tragedia sobre la duda, la traición y la justicia.", "Literatura", True),
    ("Macbeth", "William Shakespeare", "Tragedia sobre la ambición desmedida y el poder.", "Literatura", True),
    ("Orgullo y prejuicio", "Jane Austen", "Clásico de la literatura inglesa sobre expectativas sociales y afecto.", "Literatura", True),
    ("El gran Gatsby", "F. Scott Fitzgerald", "Retrato del sueño americano y la decadencia en los años veinte.", "Literatura", True),
    ("El retrato de Dorian Gray", "Oscar Wilde", "Exploración estética sobre la juventud, la belleza y la moral.", "Literatura", True),
    ("100 Poems", "Seamus Heaney", "Antología poética del Premio Nobel irlandés.", "Literatura", True),
    ("Cumbres borrascosas", "Emily Brontë", "Pasión y venganza en los páramos ingleses.", "Literatura", True),
    ("El conde de Montecristo", "Alexandre Dumas", "La historia épica de justicia, traición y venganza.", "Literatura", True),
    ("Palabras que venden", "Phil M. Jones", "Frases mágicas e influencia verbal para la comunicación efectiva y las ventas.", "Ventas", False),
    ("El hombre más rico de Babilonia", "George S. Clason", "Parábolas clásicas sobre el ahorro, la inversión y la gestión del dinero.", "Finanzas", False),
    ("Dinero: Domina el juego", "Tony Robbins", "Guía paso a paso para la libertad financiera basada en entrevistas a grandes inversionistas.", "Finanzas", False),
    ("La vía rápida del millonario", "M.J. DeMarco", "Crítica a las rutas financieras tradicionales y mapa para crear riqueza activa.", "Finanzas", False),
    ("Háblame para que te escuche", "Adele Faber y Elaine Mazlish", "Técnicas de comunicación empática y resolución de conflictos interpersonales.", "Comunicación", False),
    ("El poder de la empatía", "Helen Riess", "Neurociencia y práctica de la empatía para mejorar la conexión humana y el liderazgo.", "Comunicación", False),
    ("Piense y hágase rico", "Napoleon Hill", "El clásico sobre la mentalidad de logro, la perseverancia y el éxito financiero.", "Finanzas", False),
    ("The Art of Spending Money", "Morgan Housel", "Reflexión sobre el arte de gastar el dinero con propósito y felicidad.", "Finanzas", True),
    ("Storytelling with Data", "Cole Nussbaumer Knaflic", "Cómo presentar hallazgos para que una gerencia actúe.", "Comunicación", True),
    ("Show Your Work!", "Austin Kleon", "10 maneras de compartir tu creatividad y hacerte descubrir.", "Carrera", True),
    ("The Tech Resume Inside Out", "Gergely Orosz", "Cómo escribir un currículum que supere filtros.", "Carrera", True),
    ("Cracking the Coding Interview", "Gayle Laakmann McDowell", "Preparación para entrevistas técnicas.", "Entrevistas", True),
    ("On Writing Well", "William Zinsser", "La guía clásica para escribir en prosa clara y convincente.", "Redacción", True),
    ("The Elements of Style", "William Strunk Jr.", "Principios fundamentales de gramática y estilo en inglés.", "Redacción", True),
    ("Steal Like an Artist", "Austin Kleon", "Manifiesto sobre la creatividad en la era digital.", "Creatividad", True),
    ("Resonate", "Nancy Duarte", "Cómo crear presentaciones visuales persuasivas.", "Comunicación", True),
    ("How to Win Friends and Influence People", "Dale Carnegie", "Habilidades interpersonales y de comunicación.", "Relaciones", True),
    ("Ego is the Enemy", "Ryan Holiday", "Cómo mantener la humildad y la objetividad profesional.", "Psicología", True),
    ("Drive", "Daniel H. Pink", "La motivación intrínseca: autonomía, maestría y propósito.", "Psicología", True),
    ("Flow", "Mihaly Csikszentmihalyi", "La psicología de la experiencia óptima y el estado de flujo.", "Psicología", True),
    ("La condición humana", "Hannah Arendt", "Análisis sobre la labor, el trabajo y la acción política.", "Filosofía", True),
    ("El choque de civilizaciones", "Samuel P. Huntington", "Análisis de la política mundial en la era posguerra fría.", "Geopolítica", True),
    ("El origen de las especies", "Charles Darwin", "La teoría fundamental de la evolución por selección natural.", "Ciencia", True),
    ("Madame Bovary", "Gustave Flaubert", "La búsqueda de la pasión frente a la monotonía burguesa.", "Literatura", True),
    ("La metamorfosis y otros relatos", "Franz Kafka", "Antología de cuentos fundamentales de Kafka.", "Literatura", True),
    ("El jugador", "Fiódor Dostoyevski", "Novela sobre la adicción al juego y el azar en las relaciones humanas.", "Literatura", True),
    ("Veinte poemas de amor y una canción desesperada", "Pablo Neruda", "La poesía lírica hispanoamericana más célebre.", "Literatura", True),
    ("El amor en los tiempos del cólera", "Gabriel García Márquez", "Historia de amor y paciencia a lo largo de décadas.", "Literatura", True),
    ("La ciudad y los perros", "Mario Vargas Llosa", "Novela ambientada en el colegio militar Leoncio Prado.", "Literatura", True),
    ("La tía Julia y el escribidor", "Mario Vargas Llosa", "Novela semiautobiográfica y comedia romántica urbana.", "Literatura", True),
    ("Los detectives salvajes", "Roberto Bolaño", "La búsqueda de la poeta Cesárea Tinajero por México y el mundo.", "Literatura", True),
    ("2666", "Roberto Bolaño", "Novela monumental sobre el mal, la literatura y la violencia contemporánea.", "Literatura", True),
    ("La insoportable levedad del ser", "Milan Kundera", "Reflexión filosófica sobre la libertad, el amor y el destino.", "Literatura", True),
    ("The Culture Map", "Erin Meyer", "Navegar las diferencias culturales en entornos globales.", "Cultura", True),
    ("The Express Entry & Overseas Career Guide", "Immigration Experts", "Planificación de relocalización internacional.", "Inmigración", True),
    ("Getting to Yes", "Roger Fisher y William Ury", "Principios de negociación ganar-ganar para ofertas de trabajo.", "Negociación", True),
    ("Working Backward", "Colin Bryar", "Prácticas de ejecución y cultura operacional dentro de Amazon.", "Gestión", True),
    ("The Software Engineer's Guidebook", "Gergely Orosz", "Manual de carrera de ingeniero junior a director técnico.", "Carrera", True),
    ("Por qué fracasan los países", "Daron Acemoglu", "El papel de las instituciones inclusivas en la prosperidad.", "Economía", True),
    ("El siglo de China", "Henry Kissinger", "Análisis histórico de las relaciones geopolíticas globales.", "Geopolítica", True),
    ("Diplomacia", "Henry Kissinger", "Historia de las relaciones internacionales desde Westfalia.", "Geopolítica", True),
    ("Postguerra: Una historia de Europa desde 1945", "Tony Judt", "Historia exhaustiva del continente europeo tras la Segunda Guerra Mundial.", "Historia", True),
    ("En el camino (On the Road)", "Jack Kerouac", "Obra cumbre de la generación beat sobre la libertad de viajar.", "Literatura", True),
    ("El corazón de las tinieblas", "Joseph Conrad", "Un viaje al interior del Congo y la naturaleza de la civilización.", "Literatura", True),
    ("Viaje al centro de la tierra", "Julio Verne", "Aventura clásica de exploración científica subterránea.", "Literatura", True),
    ("La vuelta al mundo en ochenta días", "Julio Verne", "El reto clásico de circunnavegación y precisión.", "Literatura", True),
    ("Un tranvía llamado Deseo", "Tennessee Williams", "Obra teatral sobre el choque entre fantasía y realidad.", "Literatura", True),
    ("La náusea", "Jean-Paul Sartre", "La obra filosófica existencialista sobre la experiencia de existir.", "Filosofía", True),
    ("Designing Connected Products", "Claire Rowland", "Diseño de productos conectados e infraestructuras IoT.", "IoT", True),
    ("Site Reliability Engineering (SRE)", "Betsy Beyer et al.", "Prácticas de confiabilidad y operación a gran escala.", "SRE", True),
    ("Building Microservices", "Sam Newman", "Diseño y modelado de microservicios acoplados libremente.", "Arquitectura", True),
    ("Industrial IoT Architectures and Protocols", "Alasdair Gilchrist", "Integración de redes OT e IT en minería e industria.", "IoT", True),
    ("Software Architecture in Practice", "Len Bass et al.", "Principios fundamentales de arquitectura de software.", "Arquitectura", True),
    ("Clean Architecture", "Robert C. Martin", "Estructuración de componentes y capas de software mantenibles.", "Arquitectura", True),
    ("Enterprise Integration Patterns", "Gregor Hohpe", "Patrones de diseño para integración de sistemas corporativos.", "Arquitectura", True),
    ("Domain-Driven Design", "Eric Evans", "Modelado de software complejo a partir del dominio de negocio.", "Arquitectura", True),
    ("Distributed Systems: Principles and Paradigms", "Andrew S. Tanenbaum", "Principios teóricos y prácticos de sistemas distribuidos.", "Sistemas", True),
    ("High Performance Browser Networking", "Ilya Grigorik", "Protocolos de red (HTTP/2, WebSockets, TLS) y optimización de latencia.", "Redes", True),
    ("El diseño de las cosas cotidianas", "Don Norman", "Diseño centrado en el usuario e interacción con máquinas.", "Diseño", True),
    ("Estructuras o por qué las cosas no se caen", "J.E. Gordon", "Principios de física e ingeniería estructural explicados de forma amena.", "Ingeniería", True),
    ("Skunk Works", "Ben R. Rich", "Memorias sobre la ingeniería secreta de Lockheed y proyectos avanzados.", "Ingeniería", True),
    ("Invención e innovación", "Vaclav Smil", "Breve historia de las tecnologías que prometieron cambiar el mundo.", "Historia", True),
    ("Energía y civilización: Una historia", "Vaclav Smil", "El papel de la energía en la evolución de las sociedades humanas.", "Historia", True),
    ("Think Stats", "Allen B. Downey", "Estadística enseñada con código Python en vez de tablas. Gratuito en el sitio del autor.", "Estadística", True, "https://allendowney.github.io/ThinkStats/"),
    ("Practical Statistics for Data Scientists", "Peter y Andrew Bruce", "Los conceptos estadísticos que realmente usas en el trabajo, sin el relleno de un curso académico.", "Estadística", True, OL + "Practical+Statistics+for+Data+Scientists"),
    ("Fluent Python", "Luciano Ramalho", "Python profundo: generadores, descriptores, asyncio. El salto de escribir scripts a escribir librerías.", "Python", True, OL + "Fluent+Python"),
    ("Why Machines Learn", "Anil Ananthaswamy", "La matemática elegante detrás del aprendizaje automático, contada como historia intelectual.", "Divulgación", True, OL + "Why+Machines+Learn"),
    ("Designing Machine Learning Systems", "Chip Huyen", "El libro que convierte científicos de datos en ingenieros: datos, features, despliegue, monitoreo y organización.", "ML Systems", True, "https://huyenchip.com/books/"),
    ("Machine Learning Engineering", "Andriy Burkov", "El proceso completo de un proyecto ML del mundo real, con los errores que nadie te cuenta. Lectura libre en el sitio.", "ML Systems", True, "http://www.mlebook.com/wiki/doku.php"),
    ("The Hundred-Page Machine Learning Book", "Andriy Burkov", "Todo el campo condensado con rigor. Ideal para repasar antes de una entrevista.", "Referencia", True, "https://themlbook.com/"),
    ("Interpretable Machine Learning", "Christoph Molnar", "SHAP, LIME, PDP y modelos intrínsecamente interpretables. Gratuito online y obligatorio si un supervisor debe confiar en tu predicción.", "Explicabilidad", True, "https://christophm.github.io/interpretable-ml-book/"),
    ("Approaching (Almost) Any Machine Learning Problem", "Abhishek Thakur", "Recetario práctico de un Kaggle Grandmaster: validación, encoding, tuning y ensambles.", "Práctica", True, OL + "Approaching+Almost+Any+Machine+Learning+Problem"),
    ("Pattern Recognition and Machine Learning", "Christopher Bishop", "El tratado bayesiano clásico. Difícil, pero es la fuente de la que beben los papers. PDF liberado por Microsoft.", "Estadística", True, "https://www.microsoft.com/en-us/research/publication/pattern-recognition-machine-learning/"),
    ("Causal Inference: The Mixtape", "Scott Cunningham", "Diferencias-en-diferencias, variables instrumentales y regresión discontinua. Gratuito online.", "Causalidad", True, "https://mixtape.scunning.com/"),
    ("The Book of Why", "Judea Pearl", "Por qué la estadística tradicional no puede responder '¿qué pasa si intervengo?' y cómo los grafos causales sí.", "Causalidad", True, OL + "The+Book+of+Why"),
    ("Build a Large Language Model (From Scratch)", "Sebastian Raschka", "Implementas tokenizer, atención, pre-entrenamiento y fine-tuning línea por línea en PyTorch. El repo con todo el código es público.", "LLMs", True, "https://github.com/rasbt/LLMs-from-scratch"),
    ("Hands-On Large Language Models", "Jay Alammar y Maarten Grootendorst", "Ilustrado y práctico: embeddings, búsqueda semántica, fine-tuning y agentes. Notebooks abiertos.", "LLMs", True, "https://github.com/HandsOnLLM/Hands-On-Large-Language-Models"),
    ("The Illustrated Transformer", "Jay Alammar", "La explicación visual que hace que la atención por fin tenga sentido. Gratuita en su blog.", "Transformers", True, "https://jalammar.github.io/illustrated-transformer/"),
    ("Prompt Engineering for LLMs", "John Berryman y Albert Ziegler", "Diseño de contexto y evaluación de prompts desde la experiencia de construir GitHub Copilot.", "Prompting", True, OL + "Prompt+Engineering+for+LLMs"),
    ("Constitutional AI y alignment: lecturas de Anthropic", "Anthropic Research", "RLHF, Constitutional AI y red teaming. Si despliegas un asistente en una operación, esto es parte del trabajo.", "Seguridad", True, "https://www.anthropic.com/research"),
    ("Understanding Deep Learning", "Simon J.D. Prince", "Las mejores figuras del campo. PDF gratuito, con notebooks y slides por capítulo.", "Deep Learning", True, "https://udlbook.github.io/udlbook/"),
    ("Deep Learning (libro de Goodfellow, versión web)", "Goodfellow, Bengio y Courville", "El texto canónico de redes profundas, leíble gratis en su sitio oficial.", "Deep Learning", True, "https://www.deeplearningbook.org/"),
    ("Deep Learning with PyTorch", "Stevens, Antiga y Viehmann", "Escrito por el equipo de PyTorch: del tensor a un proyecto médico completo. PDF gratuito en pytorch.org.", "PyTorch", True, "https://pytorch.org/assets/deep-learning/Deep-Learning-with-PyTorch.pdf"),
    ("The Little Book of Deep Learning", "François Fleuret", "Todo el campo en unas 170 páginas en formato móvil. Perfecto para repasar en el bus.", "Referencia", True, "https://fleuret.org/francois/lbdl.html"),
    ("Deep Learning: Foundations and Concepts", "Christopher y Hugh Bishop", "La actualización 2024 del clásico de Bishop, ya con transformers y modelos de difusión.", "Deep Learning", True, "https://www.bishopbook.com/"),
    ("Deep Learning for Coders with fastai and PyTorch", "Jeremy Howard y Sylvain Gugger", "El libro del curso fast.ai. Los notebooks completos están en GitHub.", "Deep Learning", True, "https://github.com/fastai/fastbook"),
    ("Machine Learning with PyTorch and Scikit-Learn", "Sebastian Raschka", "Puente entre ML clásico y deep learning con el mismo código y las mismas convenciones.", "Deep Learning", True, "https://github.com/rasbt/machine-learning-book"),
    ("The Deep Learning Revolution", "Terrence Sejnowski", "Historia contada por dentro: de las redes de los ochenta al boom actual.", "Divulgación", True, OL + "The+Deep+Learning+Revolution"),
    ("Genius Makers", "Cade Metz", "La crónica periodística de Hinton, LeCun, Bengio y la carrera industrial por la IA.", "Divulgación", True, OL + "Genius+Makers"),
    ("El algoritmo maestro", "Pedro Domingos", "Las cinco tribus del machine learning y la búsqueda de un algoritmo universal de aprendizaje.", "Divulgación", False, OL + "El+algoritmo+maestro"),
    ("Machine Learning Design Patterns", "Lakshmanan, Robinson y Munn", "30 patrones repetibles para problemas de diseño de sistemas ML, con código en GitHub.", "ML Systems", True, "https://github.com/GoogleCloudPlatform/ml-design-patterns"),
    ("Building Machine Learning Powered Applications", "Emmanuel Ameisen", "De la idea al producto: definición del problema, iteración y despliegue con criterio de producto.", "ML Systems", True, "https://github.com/hundredblocks/ml-powered-applications"),
    ("Practical MLOps", "Noah Gift y Alfredo Deza", "Operacionalización de modelos en AWS, Azure y GCP con enfoque DevOps.", "MLOps", True, OL + "Practical+MLOps"),
    ("Reliable Machine Learning", "Cathy Chen et al.", "SRE aplicado a ML: SLOs para modelos, on-call e incidentes de datos. Escrito por gente de Google.", "SRE", True, OL + "Reliable+Machine+Learning"),
    ("Site Reliability Engineering (libro completo, gratis)", "Google", "El libro que definió el oficio de operar sistemas. Lectura íntegra en el sitio de Google SRE.", "SRE", True, "https://sre.google/sre-book/table-of-contents/"),
    ("Data Mesh", "Zhamak Dehghani", "Descentralización del dato como producto. Relevante cuando el ML depende de datos de varias áreas.", "Arquitectura", True, OL + "Data+Mesh+Dehghani"),
    ("The Phoenix Project", "Gene Kim", "Novela sobre DevOps que explica, mejor que cualquier manual, por qué los despliegues manuales matan equipos.", "DevOps", True, OL + "The+Phoenix+Project"),
    ("Release It!", "Michael Nygard", "Patrones de estabilidad —circuit breakers, bulkheads, timeouts— para servicios que no pueden caerse.", "Arquitectura", True, OL + "Release+It+Nygard"),
    ("Kubernetes Up & Running", "Brendan Burns et al.", "Fundamentos de Kubernetes por uno de sus creadores.", "Kubernetes", True, OL + "Kubernetes+Up+and+Running"),
    ("Observability Engineering", "Charity Majors et al.", "Trazas, métricas y logs con alta cardinalidad. Cómo saber qué está pasando dentro de tu sistema.", "Monitoreo", True, OL + "Observability+Engineering"),
    ("LLM Engineer's Handbook", "Paul Iusztin y Maxime Labonne", "Ciclo completo de un producto LLM: datos, fine-tuning, RAG, despliegue y monitoreo, en un solo proyecto. Repo público.", "LLMs", True, "https://github.com/PacktPublishing/LLM-Engineers-Handbook"),
    ("AI Engineering", "Chip Huyen", "El libro de referencia del rol: modelos fundacionales, evaluación, RAG, agentes y costos.", "AI Engineering", True, "https://huyenchip.com/books/"),
    ("Speech and Language Processing (3.ª ed., borrador gratuito)", "Jurafsky y Martin", "La biblia del NLP, actualizada con LLMs y disponible en PDF desde Stanford.", "NLP", True, "https://web.stanford.edu/~jurafsky/slp3/"),
    ("Designing Large Language Model Applications", "Suhas Pai", "Arquitectura de aplicaciones LLM: decisiones de diseño, trade-offs y patrones de producción.", "LLM Apps", True, OL + "Designing+Large+Language+Model+Applications"),
    ("Generative Deep Learning", "David Foster", "VAE, GAN, difusión y modelos autoregresivos explicados con código. Repo público.", "Generative AI", True, "https://github.com/davidADSP/Generative_Deep_Learning_2nd_Edition"),
    ("The Alignment Problem", "Brian Christian", "Cómo hacer que los sistemas de IA hagan lo que queremos. Técnico y filosófico a la vez.", "Alignment", True, OL + "The+Alignment+Problem"),
    ("Human Compatible", "Stuart Russell", "El coautor del libro canónico de IA sobre cómo diseñar máquinas que sigan siendo controlables.", "Alignment", True, OL + "Human+Compatible"),
    ("Co-Intelligence: Living and Working with AI", "Ethan Mollick", "Cómo cambia el trabajo real con LLMs de por medio. Útil para vender proyectos internamente.", "Trabajo", True, OL + "Co-Intelligence+Mollick"),
    ("Atlas of AI", "Kate Crawford", "El costo material de la IA: minería de litio, energía y trabajo humano. Ironía útil para quien viene de minería.", "Sociedad", True, OL + "Atlas+of+AI"),
    ("Machine Learning System Design Interview", "Ali Aminian y Alex Xu", "Siete casos de diseño resueltos con el marco de respuesta que esperan los entrevistadores.", "Entrevistas", True, OL + "Machine+Learning+System+Design+Interview"),
    ("Deep Learning Interviews", "Shlomo Kashani", "Cientos de problemas resueltos de matemática, ML clásico y deep learning. Gratuito en arXiv.", "Entrevistas", True, "https://arxiv.org/abs/2201.00650"),
    ("Ace the Data Science Interview", "Kevin Huo y Nick Singh", "Preguntas de SQL, estadística, ML y producto, con soluciones.", "Entrevistas", True, OL + "Ace+the+Data+Science+Interview"),
    ("Artificial Intelligence: A Modern Approach", "Stuart Russell y Peter Norvig", "El libro canónico de IA. No lo lees entero: lo consultas toda la carrera.", "Referencia", True, "https://aima.cs.berkeley.edu/"),
    ("The Staff Engineer's Path", "Tanya Reilly", "Cómo crece un ingeniero técnico sin volverse gerente: influencia, alcance y decisiones de arquitectura.", "Carrera", True, OL + "The+Staff+Engineer%27s+Path"),
    ("Staff Engineer: Leadership Beyond the Management Track", "Will Larson", "Los arquetipos de ingeniero senior y cómo llegar a ellos. Lectura libre en staffeng.com.", "Carrera", True, "https://staffeng.com/book/"),
    ("A Philosophy of Software Design", "John Ousterhout", "Complejidad, profundidad de módulos y diseño incremental. Corto y de los mejores libros de software escritos.", "Diseño", True, OL + "A+Philosophy+of+Software+Design"),
    ("The Art of Doing Science and Engineering", "Richard Hamming", "Las conferencias de Hamming sobre cómo hacer trabajo que importe y elegir problemas grandes.", "Carrera", True, OL + "The+Art+of+Doing+Science+and+Engineering"),
    ("So Good They Can't Ignore You", "Cal Newport", "El capital de carrera se construye con habilidades raras y valiosas, no siguiendo la pasión.", "Carrera", True, OL + "So+Good+They+Can%27t+Ignore+You"),
    ("Deep Work", "Cal Newport", "Concentración sostenida como ventaja competitiva. Aplicable directo a un plan de estudio de dos años.", "Productividad", True, OL + "Deep+Work+Newport"),
    ("Prediction Machines", "Agrawal, Gans y Goldfarb", "La IA vista como una caída en el costo de predecir. El marco económico para justificar proyectos ante dirección.", "Negocio", True, OL + "Prediction+Machines"),
    ("Competing in the Age of AI", "Marco Iansiti y Karim Lakhani", "Cómo se reorganizan las empresas alrededor de datos y modelos.", "Negocio", True, OL + "Competing+in+the+Age+of+AI"),
    ("The Worlds I See", "Fei-Fei Li", "Memorias de la creadora de ImageNet: inmigración, ciencia y la construcción de la visión por computadora moderna.", "Divulgación", True, OL + "The+Worlds+I+See"),
    ("Chip War", "Chris Miller", "La guerra geopolítica por los semiconductores que hacen posible todo esto.", "Geopolítica", True, OL + "Chip+War"),
]


class Command(BaseCommand):
    help = "Carga la biblioteca completa en su etapa oculta dentro de la ruta enfocada."

    def add_arguments(self, parser):
        parser.add_argument(
            "--quitar", action="store_true", help="Borra la biblioteca entera."
        )

    @transaction.atomic
    def handle(self, *args, **opciones):
        if opciones["quitar"]:
            borrados, _ = Etapa.objects.filter(
                ruta=Etapa.Ruta.ENFOCADA, orden=ORDEN_BIBLIOTECA
            ).delete()
            self.stdout.write(
                self.style.WARNING(f"Biblioteca borrada ({borrados} registros).")
            )
            return

        etapa, _ = Etapa.objects.update_or_create(
            ruta=Etapa.Ruta.ENFOCADA,
            orden=ORDEN_BIBLIOTECA,
            defaults={
                "kicker": "Lectura",
                "titulo": "Biblioteca",
                "subtitulo": "Sin fecha y sin orden",
                "objetivo": "Los libros no se planifican: se leen cuando toca.",
                "color": "#c2703d",
                "oculta": True,
            },
        )

        nuevos = 0
        for i, fila in enumerate(LIBROS):
            titulo, fuente, detalle, etiqueta = fila[:4]
            en_ingles = fila[4] if len(fila) > 4 else False
            url = fila[5] if len(fila) > 5 else ""
            obj, creado = Item.objects.get_or_create(
                etapa=etapa,
                titulo=titulo,
                defaults={
                    "tipo": Item.Tipo.LIBRO,
                    "fuente": fuente,
                    "detalle": detalle,
                    "etiqueta": etiqueta,
                    "en_ingles": en_ingles,
                    "url": url or OL + quote_plus(titulo),
                    "orden": i,
                },
            )
            nuevos += creado
            if not creado and not obj.url:
                obj.url = url or OL + quote_plus(titulo)
                obj.save(update_fields=["url"])

        self.stdout.write(
            self.style.SUCCESS(
                f"Biblioteca lista: {etapa.items.count()} libros ({nuevos} nuevos)."
            )
        )
